export { Login } from "./Auth/Login"
export { Signup } from "./Auth/Signup"
export { Home } from "./Home/Home"
export { Notes } from "./Notes/Notes"
export { Archives } from "./Archives/Archives"
export { Trash } from "./Trash/Trash"